name: Counter Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pyinstaller pytest-mock  # Add pytest-mock here

      - name: Navigate to counter/usr/local/bin directory
        run: cd counter/usr/local/bin

      - name: Debug repository contents
        run: |
          cd counter/usr/local/bin
          ls -la
          cat Makefile

      - name: Build project
        run: |
          cd counter/usr/local/bin
          make build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install test dependencies
        run: |
          pip install pytest pytest-mock  # Add pytest-mock here

      - name: Navigate to counter/usr/local/bin directory
        run: cd counter/usr/local/bin

      - name: Run tests
        run: |
          cd counter/usr/local/bin
          make test

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pytest-mock  # Add pytest-mock here

      - name: Navigate to counter/usr/local/bin directory
        run: cd counter/usr/local/bin

      - name: Build Debian package
        run: |
          cd counter/usr/local/bin
          make build-deb

      - name: Upload .deb as artifact
        uses: actions/upload-artifact@v4
        with:
          name: counter-deb-package
          path: counter/usr/local/bin/counter_service-v2.0.0.deb

  lint:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pytest-mock  # Add pytest-mock here

      - name: Install lintian
        run: |
          sudo apt-get update
          sudo apt-get install -y lintian

      - name: Navigate to counter/usr/local/bin directory
        run: cd counter/usr/local/bin

      - name: Lint Debian package
        run: |
          cd counter/usr/local/bin
          make lint-deb